server:
  port: 8080

spring:
  application:
    name: project
  datasource:
    url: jdbc:h2:mem:rs
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  api-docs:
    enabled: true
    path: /docs/api-docs
  swagger-ui:
    path: /docs/swagger
    display-request-duration: true
    tags-sorter: alpha
    enabled: true
  override-with-generic-response: false

swagger:
  info:
    title: R-SUPPORT API
    description: R-SUPPORT API
    version: 1.0.1
    contact:
      name: https://www.rsupport.com/
      url: https://www.rsupport.com/
      email:  https://www.rsupport.com/

